# Generated by Django 3.2 on 2024-04-08 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tokenuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenuser',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 15, 17, 58, 22, 791851)),
        ),
    ]
