# Generated by Django 3.2 on 2024-04-08 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_tokenuser_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenuser',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 15, 12, 29, 4, 700920)),
        ),
    ]
